# pseudo actions

name: hell-o
env:
  APP_NAME: "some appName"
  VAR1    : "value 1: ${{ github.sha }}"


on:
  push:
    branches: 
      - main

jobs:
  job_A:
    runs-on: ubuntu-latest
    steps:
    - name: Echo 1
      run : |
        echo 'hell-o'
        echo "${{ env.APP_NAME }}"
  
  job_2:
    runs-on: ubuntu-latest
    steps:
    - name: Echo 2
      run : echo 'in job_B'

  after-all:
    runs-on: ubuntu-latest
    needs: [job_A, job_2]
    steps:
    - name: Echo Fin
      run : echo 'after all' && echo ${{ env.VAR1 }}
#
