name: Makefile-CI

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: make help
      run: make

    - name: Run clean
      run: make clean
