name: self-hosted
on: [workflow_dispatch]
jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: first step
        run : echo 'the very first step'
      - name: clone Repo
        uses: actions/checkout@v3
      - name: pause
        run : |
          echo 'pause..'
          sleep 180
          echo '..awake'
