name: self-hosted
on: [workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu_latest # self-hosted
    steps:
      - name: first step
        run : echo 'the very first step'
      - name: clone Repo
        uses: actions/checkout@v3
      - name: pause
        run : |
          echo 'pause..'
          sleep 1
          echo '..awake'
